set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86)

set(CUSTOMMODEL_MINGW_PREFIX "i686-w64-mingw32" CACHE STRING
    "Prefix used by the 32-bit MinGW-w64 cross compiler"
)

find_program(CMAKE_CXX_COMPILER
    NAMES "${CUSTOMMODEL_MINGW_PREFIX}-g++"
    REQUIRED
)

find_program(CMAKE_RC_COMPILER
    NAMES "${CUSTOMMODEL_MINGW_PREFIX}-windres"
)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
